### ISSUE TITLE
Error in windows service install syntax

### ISSUE THREAD

**Issue by remcoveugen** [KofaxRPA/Robot-Lifecycle-Management-Guide#1]
Chapter 7 : 32

ServiceInstaller.exe -c Synchronizer.conf wrapper.syslog.loglevel=INFO wrapper.ntservice.starttype=AUTO_START wrapper.ntservice.name="Kofax RPA
11.0.0.1 Synchronizer" |  

Should be :

ServiceInstaller.exe -i Synchronizer.conf wrapper.syslog.loglevel=INFO wrapper.ntservice.starttype=AUTO_START wrapper.ntservice.name="Kofax RPA
11.0.0.1 Synchronizer" |

**Comment by TungstenRPA** [comment]
Thanks Remco for reporting this!
